#! /bin/sh
# kcminputrc Mouse cursorTheme 'breeze_cursors'
kcminputrc_mouse_cursortheme=breeze_cursors
# kcminputrc Mouse cursorSize ''
kcminputrc_mouse_cursorsize=''
# ksplashrc KSplash Theme Breeze
ksplashrc_ksplash_theme=Breeze
# ksplashrc KSplash Engine KSplashQML
ksplashrc_ksplash_engine=KSplashQML
# kdeglobals KScreen ScreenScaleFactors ''
kdeglobals_kscreen_screenscalefactors='DVI-I-0=1.2;DVI-I-1=1.2;HDMI-0=1.2;DP-0=1.2;DVI-D-0=1.2;DP-1=1.2;'
# kcmfonts General forceFontDPI 0
kcmfonts_general_forcefontdpi=115
